In [1]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
data

[[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [2]:
import pandas as pd
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [3]:
#实现归一化
scaler = MinMaxScaler() #实例化
scaler = scaler.fit(data)  #本质上是生成min(x)与max(x)
result = scaler.transform(data) #通过接口导出结果

In [4]:
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [5]:
result_ = scaler.fit_transform(data)  #训练和导出结果一步达成
result_

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [6]:
scaler.inverse_transform(result)  #将归一化后的结果逆转

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [7]:
#使用feature_range实现将数据缩放到[0，1]之外的其他范围。
scaler = MinMaxScaler(feature_range=[5,10])
result = scaler.fit_transform(data)

In [8]:
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [9]:
#使用numpy来实现归一化
import numpy as np
X = np.array([[-1,2],[-0.5,6],[0,10],[1,18]])

In [10]:
X

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [12]:
X_nor = (X - X.min(axis=0)) / (X.max(axis=0) + X.min(axis=0))
X_nor
# ?

D:\conda\envs\py36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\conda\envs\py36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0. ],
       [inf, 0.2],
       [inf, 0.4],
       [inf, 0.8]])